# Generated by Django 3.2.2 on 2021-07-28 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Organizers have accepted the registration'),
        ),
        migrations.AddField(
            model_name='registration',
            name='accepted_email_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='access_code',
            field=models.CharField(blank=True, editable=False, help_text='A short random code used to process an application in the URL.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='User has confirmed their acceptance'),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_total_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='rejection_list_email_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_canceled',
            field=models.BooleanField(default=False, help_text='User has canceled their registration'),
        ),
        migrations.AddField(
            model_name='registration',
            name='waiting_list',
            field=models.BooleanField(default=False, help_text='A non-accepted registration is on the waiting list in case there is space'),
        ),
        migrations.AddField(
            model_name='registration',
            name='waiting_list_email_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=32)),
                ('email_content', models.TextField()),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.registration')),
            ],
        ),
    ]
