# Generated by Django 3.2.2 on 2021-07-28 22:54
import random
import string
from django.db import migrations


def create_access_codes(apps, schema_editor):
    Registration = apps.get_model('registration', 'Registration')
    for registration in Registration.objects.filter(access_code=None):
        registration.access_code = ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(12))
        registration.save()

def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_process'),
    ]

    operations = [
        migrations.RunPython(create_access_codes, reverse_code=noop),
    ]
