# Generated by Django 3.2.2 on 2021-07-29 19:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_alter_registration_access_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="dietary_restrictions",
            field=models.TextField(blank=True, verbose_name="Dietary restrictions"),
        ),
        migrations.AddField(
            model_name="registration",
            name="scholarship_accomodation",
            field=models.BooleanField(
                default=False,
                help_text="We will provide accommodation nearby the venue",
                verbose_name="I need accommodation",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="scholarship_other_needs",
            field=models.TextField(
                blank=True,
                help_text="Please indicate need + cost (MK or $)",
                verbose_name="Other needs",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="scholarship_transportation",
            field=models.BooleanField(
                default=False, verbose_name="I need transportation support"
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="scholarship_transportation_departure",
            field=models.CharField(
                help_text="Tell us where you are traveling from. Please indicate city/district (if Lilongwe), country",
                max_length=1024,
                null=True,
                verbose_name="Departure place",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="tshirt_color",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("blue", "Blue (event's theme color)"),
                    ("white", "White"),
                    ("grey", "Grey"),
                ],
                max_length=32,
                null=True,
                verbose_name="T-shirt color preference",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="tshirt_fit",
            field=models.CharField(
                choices=[("women", "Women's fit"), ("men", "Men's fit")],
                max_length=16,
                null=True,
                verbose_name="T-shirt sizes",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="tshirt_size",
            field=models.CharField(
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                    ("2xl", "2xl"),
                    ("3xl", "3xl"),
                ],
                max_length=3,
                null=True,
                verbose_name="T-shirt sizes",
            ),
        ),
    ]
