# Generated by Django 3.2.2 on 2021-08-24 14:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_python_week_of_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes that are internal, some are auto-generated",
                verbose_name="Internal notes",
            ),
        ),
        migrations.AddField(
            model_name="registrationweek1",
            name="internal_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes that are internal, some are auto-generated",
                verbose_name="Internal notes",
            ),
        ),
    ]
