# Generated by Django 3.2.2 on 2021-09-17 22:33
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_massmail"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="has_laptop",
            field=models.BooleanField(
                default=False,
                help_text="We encourage to bring your own laptop, such that you can keep software installed after the event and make your own notes etc. Otherwise, computers are available at the event, too",
                verbose_name="Bringing a laptop",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="registration_receipt",
            field=models.FileField(
                blank=True,
                help_text="For your payment of the registration fee: Before October 1st, provide an image/scan of bank deposit slip (receipt from transfer)",
                null=True,
                upload_to="receipts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "odt",
                            "jpeg",
                            "png",
                            "jpg",
                        ]
                    )
                ],
                verbose_name="Bank deposit slip",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="reimbursement_account_number",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Reimbursement account number",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="reimbursement_account_owner",
            field=models.CharField(
                blank=True,
                help_text="Name of the account owner, this MUST be you! But please put it correctly",
                max_length=128,
                null=True,
                verbose_name="Reimbursement account owner",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="reimbursement_bank_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the bank in which you hold an account (National Bank preferred)",
                max_length=128,
                null=True,
                verbose_name="Reimbursement bank name",
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="reimbursement_branch_code",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Reimbursement branch code",
            ),
        ),
        migrations.AddField(
            model_name="registrationweek1",
            name="has_laptop",
            field=models.BooleanField(
                default=False,
                help_text="We encourage to bring your own laptop, such that you can keep software installed after the event and make your own notes etc. Otherwise, computers are available at the event, too",
                verbose_name="Bringing a laptop",
            ),
        ),
        migrations.AddField(
            model_name="registrationweek1",
            name="registration_receipt",
            field=models.FileField(
                blank=True,
                help_text="For your payment of the registration fee: Before October 1st, provide an image/scan of bank deposit slip (receipt from transfer)",
                null=True,
                upload_to="receipts",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "odt",
                            "jpeg",
                            "png",
                            "jpg",
                        ]
                    )
                ],
                verbose_name="Bank deposit slip",
            ),
        ),
        migrations.AddField(
            model_name="registrationweek1",
            name="reimbursement_account_number",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Reimbursement account number",
            ),
        ),
        migrations.AddField(
            model_name="registrationweek1",
            name="reimbursement_account_owner",
            field=models.CharField(
                blank=True,
                help_text="Name of the account owner, this MUST be you! But please put it correctly",
                max_length=128,
                null=True,
                verbose_name="Reimbursement account owner",
            ),
        ),
        migrations.AddField(
            model_name="registrationweek1",
            name="reimbursement_bank_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the bank in which you hold an account (National Bank preferred)",
                max_length=128,
                null=True,
                verbose_name="Reimbursement bank name",
            ),
        ),
        migrations.AddField(
            model_name="registrationweek1",
            name="reimbursement_branch_code",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Reimbursement branch code",
            ),
        ),
    ]
