# Generated by Django 3.2.2 on 2021-09-18 21:44
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_registration_new_fields_bank_stuff"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="scholarship_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="Is your participation in this event reliant on the Scholarship?",
                verbose_name="Participation conditioned by scholarship",
            ),
        ),
    ]
