# Generated by Django 3.2.2 on 2021-09-26 15:57
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_transportation"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="registration_week1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.registrationweek1",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="tshirt_fit",
            field=models.CharField(
                blank=True,
                choices=[("women", "Women's fit"), ("men", "Men's fit")],
                max_length=16,
                null=True,
                verbose_name="T-shirt fit",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                    ("2xl", "2xl"),
                    ("3xl", "3xl"),
                ],
                max_length=3,
                null=True,
                verbose_name="T-shirt size",
            ),
        ),
        migrations.AlterField(
            model_name="registrationweek1",
            name="tshirt_fit",
            field=models.CharField(
                blank=True,
                choices=[("women", "Women's fit"), ("men", "Men's fit")],
                max_length=16,
                null=True,
                verbose_name="T-shirt fit",
            ),
        ),
        migrations.AlterField(
            model_name="registrationweek1",
            name="tshirt_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("xs", "XS"),
                    ("s", "S"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xl", "XL"),
                    ("2xl", "2xl"),
                    ("3xl", "3xl"),
                ],
                max_length=3,
                null=True,
                verbose_name="T-shirt size",
            ),
        ),
    ]
