# Generated by Django 3.2.2 on 2021-10-11 08:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0012_emaillog_registration_week1"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="dry_run",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="Test email (dry run)"
            ),
        ),
        migrations.AddField(
            model_name="emaillog",
            name="massmail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.massmail",
            ),
        ),
    ]
